server:
    port:
       8089

spring:
    application:
        name:
            API_GATEWAY

    #CLOUD GATEWAY CONFIG
    cloud:
         gateway:
                 routes:
                     - id: USER-SERVICE
                       uri: lb://USER-SERVICE
                       predicates:
                          - Path=/user/**

                     - id: HOTEL-SERVICE
                       uri: lb://HOTEL-SERVICE
                       predicates:
                          - Path=/hotel/**

                     - id: RATING-SERVICE
                       uri: lb://RATING-SERVICE
                       predicates:
                          - Path=/rating/** 

#EUREKA CLIENT CONFIG.
eureka:
     client:
          register-with-eureka: true
          fetch-registry: true