server:
   port: 8081

spring:

  application:
      name: services

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Tushar()mysql[123]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true