server:
   port: 8082

spring:
   application:
       name: HOTEL-SERVICE
  
   datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: Tushar()mysql[123]
   jpa:
        hibernate:
            ddl-auto : update
        show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true